# Generated by rust2rpm 27
%bcond check 1

%global crate forgejo-cli

Name:           rust-forgejo-cli
Version:        0.2.0
Release:        %autorelease
Summary:        CLI tool for Forgejo

License:        Apache-2.0 OR MIT
URL:            https://crates.io/crates/forgejo-cli
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  openssl-devel
BuildRequires:  zlib-devel

%global _description %{expand:
CLI tool for Forgejo.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE-APACHE
%license LICENSE-MIT
%doc README.md
%{_bindir}/fj

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
# %%cargo_generate_buildrequires

%build
# Remove offline build stuff
sed -i '/\[net\]/q' .cargo/config.toml
# Oniguruma fails to compile because gcc15 defaults to std=gnu23 
export CFLAGS="$CFLAGS -std=gnu17"
%cargo_build

%install
install -Dpm 0755 target/release/fj -t %{buildroot}%{_bindir}

%if %{with check}
%check
# %%cargo_test
%endif

%changelog
%autochangelog
