# Generated by rust2rpm 27
%bcond check 1 

%global crate bottom
%global binary_name btm

Name:           bottom
Version:        0.10.2
Release:        %autorelease
Summary:        Customizable cross-platform graphical process/system monitor for the terminal

License:        MIT
URL:            https://crates.io/crates/bottom
Source:         %{crates_source}
Source1:        https://github.com/ClementTsang/bottom/releases/download/%{version}/completion.tar.gz
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          bottom-fix-metadata-auto.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A customizable cross-platform graphical process/system monitor for the
terminal. Supports Linux, macOS, and Windows.}

%description %{_description}

%files       -n %{crate}
%license LICENSE
%license LICENSE.dependencies
%doc README.md
%{_bindir}/%{binary_name}
%{bash_completions_dir}/%{binary_name}.bash
%{zsh_completions_dir}/_%{binary_name}
%{fish_completions_dir}/%{binary_name}.fish

%prep
%autosetup -n %{crate}-%{version} -p1
%autosetup -a 1

# rust version too low for EPEL 9 and below
%if 0%{?el8} || 0%{?el9}
  bash <(curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs) --profile=minimal -y
  %define __rustc $HOME/.cargo/bin/rustc
  %define __cargo /usr/bin/env CARGO_HOME=.cargo RUSTC_BOOTSTRAP=1 RUSTFLAGS='%{build_rustflags}' "$HOME/.cargo/bin/cargo"
  %define __rustdoc $HOME/.cargo/bin/rustdoc
%endif

%__cargo vendor
%cargo_prep -v vendor

%build
%cargo_build
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install
install -Dpm 0644 %{binary_name}.bash -t %{buildroot}%{bash_completions_dir}
install -Dpm 0644 %{binary_name}.fish -t %{buildroot}%{fish_completions_dir}
install -Dpm 0644 _%{binary_name} -t %{buildroot}%{zsh_completions_dir}

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
