# Generated by rust2rpm 27
%bcond check 1

Name:           yazi
Version:        25.3.2
Release:        %autorelease
Summary:        Yazi file manager

SourceLicense:  MIT
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME

URL:            https://yazi-rs.github.io 
Source:         https://github.com/sxyazi/yazi/archive/refs/tags/v%{version}.tar.gz

Requires: file
Recommends: p7zip
Recommends: p7zip-plugins
Recommends: jq
Recommends: poppler
Recommends: fd-find
Recommends: ripgrep
Recommends: fzf
Recommends: zoxide
Recommends: ImageMagick
Recommends: git

BuildRequires: cargo-rpm-macros >= 24
BuildRequires: make
%if 0%{?fedora} >= 42
BuildRequires: clang 
%else
BuildRequires: gcc
%endif
BuildRequires: git

%global _description %{expand:
Blazing fast terminal file manager written in Rust, based on async I/O.}

%description %{_description}

%prep
%autosetup -n yazi-%{version} -p1
# %%cargo_prep

%generate_buildrequires
# %%cargo_generate_buildrequires

%build
# %%cargo_build
%if 0%{?fedora} >= 42
CC=clang
%else
CC=gcc
%endif
RUSTFLAGS='-Copt-level=3 -Cdebuginfo=2 -Ccodegen-units=1 -Cstrip=none -Cforce-frame-pointers=yes' cargo build -j${RPM_BUILD_NCPUS} --release

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license LICENSE-ICONS
%license LICENSE.dependencies
%doc CODE_OF_CONDUCT.md
%doc CONTRIBUTING.md
%doc README.md
%{_bindir}/ya
%{_bindir}/yazi

%changelog
%autochangelog
