# Generated by rust2rpm 27
%bcond check 1

Name:           yazi-fm
Version:        25.3.7
Release:        %autorelease
Summary:        Yazi File Manager

SourceLicense:  MIT
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

URL:            # FIXME
Source:         # FIXME

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Yazi File Manager.}

%description %{_description}

%prep
%autosetup -n yazi-fm-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license LICENSE-ICONS
%license LICENSE.dependencies
%doc CODE_OF_CONDUCT.md
%doc CONTRIBUTING.md
%doc README.md
%{_bindir}/ya
%{_bindir}/yazi

%changelog
%autochangelog
