# Generated by go2rpm 1.16.0
%bcond check 1
%bcond bootstrap 0

%if %{with bootstrap}
%global debug_package %{nil}
%endif

%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/bazelbuild/bazelisk
%global goipath         github.com/bazelbuild/bazelisk
Version:                1.26.0

%gometa -L -f

%global common_description %{expand:
A user-friendly launcher for Bazel.}

%global golicenses      LICENSE
%global godocs          CONTRIBUTING.md README.md

Name:           bazelisk
Release:        %autorelease
Summary:        A user-friendly launcher for Bazel

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%if %{without bootstrap}
%build
%gobuild -o %{gobuilddir}/bin/bazel %{goipath}
%endif

%install
%gopkginstall
%if %{without bootstrap}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
%endif

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%if %{without bootstrap}
%files
%license LICENSE
%doc CONTRIBUTING.md README.md
%{_bindir}/bazel
%endif

%gopkgfiles

%changelog
%autochangelog
